=== pedromachado-ifsp/extension-iec61970/prosumer_cim.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

		<xs:element name="prosumer">
		
			<xs:complexType>
				<xs:sequence>
					<xs:element name="mRID" minOccurs="1" maxOccurs="1"/>
					<xs:element name="name" minOccurs="1" maxOccurs="1"/>
					<xs:element name="latitude" minOccurs="1" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
							  <xs:minInclusive value="-90"/>
							  <xs:maxInclusive value="90"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="longitude" minOccurs="1" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
							  <xs:minInclusive value="-180"/>
							  <xs:maxInclusive value="180"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="pvPlantACRatedP" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
					<xs:element name="pvPlantDCRatedP" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
					<xs:element name="commissioningDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
					<xs:element name="systemUpdate" type="xs:date" minOccurs="0" maxOccurs="1"/>
					<xs:element name="decommissioningDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
					<xs:element name="description" minOccurs="0" maxOccurs="1"/>
					<xs:element name="location" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:complexType>
		
		</xs:element>

</xs:schema>

=== pedromachado-ifsp/extension-iec61970/prosumer_instance.xml
<prosumer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="prosumer_cim.xsd">
	<mRID>UC_999.026-12</mRID>
	<name>ibirité_ifmg_usina_75kW</name>
	<latitude>-20.03</latitude>
	<longitude>-44.03</longitude>
	<pvPlantACRatedP>75000</pvPlantACRatedP>
	<pvPlantDCRatedP>100000</pvPlantDCRatedP>
	<commissioningDate>2021-05-01</commissioningDate>
	<systemUpdate>2023-02-12</systemUpdate>
	<description>Usina Fotovoltaica do IFMG Campus Ibirité</description>
	<location>R. Mato Grosso - Vista Alegre, Ibirité - MG, 32400-000</location>
</prosumer>
