=== pedromachado-ifsp/extension-iec61970/pv_array_cim.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

		<xs:element name="pv_array">
		
			<xs:complexType>
				<xs:sequence>
					<xs:element name="mRID" minOccurs="1"/>
					<xs:element name="name" minOccurs="1"/>
					<xs:element name="numberModuleInSeries" type="xs:integer" minOccurs="1" maxOccurs="1"/>
					<xs:element name="numberStringInParallel" type="xs:integer" minOccurs="1" maxOccurs="1"/>
					<xs:element name="oversizing" minOccurs="1" maxOccurs="1">
					  <xs:simpleType>
						<xs:restriction base="xs:decimal">
						  <xs:minInclusive value="0"/>
						  <xs:maxInclusive value="2"/>
						</xs:restriction>
					  </xs:simpleType>						
					</xs:element>
					<xs:element name="trackMode" minOccurs="1" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:string">
							  <xs:enumeration value="fixed"/>
							  <xs:enumeration value="one-axis track"/>
							  <xs:enumeration value="two-axis track"/>
							  <xs:enumeration value="other"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					<xs:element name="maxDCOutputVoltage" type="xs:integer" minOccurs="0" maxOccurs="1"/>
					<xs:element name="tiltAngle" minOccurs="0" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
							  <xs:minInclusive value="-60"/>
							  <xs:maxInclusive value="60"/>
							</xs:restriction>
						</xs:simpleType>	
					</xs:element>
					<xs:element name="azimuthalAngle" minOccurs="0" maxOccurs="1">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
							  <xs:minInclusive value="-180"/>
							  <xs:maxInclusive value="180"/>
							</xs:restriction>
						</xs:simpleType>	
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		
		</xs:element>

</xs:schema>

=== pedromachado-ifsp/extension-iec61970/pv_array_instance.xml
<pv_array xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="pv_array_cim.xsd">
	<mRID>array_#12</mRID>
	<name>ibiritÃ©_ifmg_array_#12</name>
	<numberModuleInSeries>10</numberModuleInSeries>
	<numberStringInParallel>3</numberStringInParallel>
	<oversizing>1.5</oversizing>
	<trackMode>one-axis track</trackMode>
	<maxDCOutputVoltage>1100</maxDCOutputVoltage>
	<tiltAngle>12.5</tiltAngle>
	<azimuthalAngle>0.3</azimuthalAngle>
</pv_array>
